// <auto-generated />
using System;
using CarPark.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarPark.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513093421_AddParkingGate")]
    partial class AddParkingGate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarPark.Models.ParkingGate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ParkingLotId");

                    b.HasIndex("UpdateBy");

                    b.ToTable("ParkingGates", (string)null);
                });

            modelBuilder.Entity("CarPark.Models.ParkingLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LotCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LotName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("ParkingLots");
                });

            modelBuilder.Entity("CarPark.Models.ParkingRateRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ApplyOnOvernight")
                        .HasColumnType("bit");

                    b.Property<int?>("BillingStepMinutes")
                        .HasColumnType("int");

                    b.Property<int>("CalculationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EndMinute")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("StartMinute")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ParkingLotId");

                    b.HasIndex("UpdateBy");

                    b.ToTable("ParkingRateRules");
                });

            modelBuilder.Entity("CarPark.Models.ParkingTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOvernight")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OutAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParkingGateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlateNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TicketNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TotalMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ParkingGateId");

                    b.HasIndex("ParkingLotId");

                    b.HasIndex("UpdateBy");

                    b.ToTable("ParkingTransactions");
                });

            modelBuilder.Entity("CarPark.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdateBy");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreateAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            MustChangePassword = true,
                            Name = "System Admin",
                            Password = "PBKDF2$SHA256$100000$CNMtqGjCwsaY4gv7R9CXhw==$lGxIuuvrpQU4rT2dzxg8Y7sbv2kmTK8mG2kMgrOUMc4=",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreateAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            MustChangePassword = true,
                            Name = "Normal User",
                            Password = "PBKDF2$SHA256$100000$W6wNPlF5a8q79g6h3inyRQ==$0N6YuOugjBTtdFCNrIBjdkXyi9B7xVfx6a75yU147r4=",
                            Role = 1,
                            Username = "user"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreateAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            MustChangePassword = true,
                            Name = "Parking Operator",
                            Password = "PBKDF2$SHA256$100000$ITDALgYVh6dezGnLr7jgFg==$Gu2S3x9mUOixGYSLAxZQqQUc1dU2xzIY2mUGT/aiYks=",
                            Role = 1,
                            Username = "operator"
                        });
                });

            modelBuilder.Entity("CarPark.Models.ParkingGate", b =>
                {
                    b.HasOne("CarPark.Models.User", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateBy");

                    b.HasOne("CarPark.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy");

                    b.HasOne("CarPark.Models.ParkingLot", "ParkingLot")
                        .WithMany("Gates")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CarPark.Models.User", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreateByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("ParkingLot");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("CarPark.Models.ParkingLot", b =>
                {
                    b.HasOne("CarPark.Models.User", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateBy");

                    b.HasOne("CarPark.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy");

                    b.HasOne("CarPark.Models.User", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreateByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("CarPark.Models.ParkingRateRule", b =>
                {
                    b.HasOne("CarPark.Models.User", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateBy");

                    b.HasOne("CarPark.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy");

                    b.HasOne("CarPark.Models.ParkingLot", "ParkingLot")
                        .WithMany("RateRules")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarPark.Models.User", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreateByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("ParkingLot");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("CarPark.Models.ParkingTransaction", b =>
                {
                    b.HasOne("CarPark.Models.User", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateBy");

                    b.HasOne("CarPark.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy");

                    b.HasOne("CarPark.Models.ParkingGate", "ParkingGate")
                        .WithMany("Transactions")
                        .HasForeignKey("ParkingGateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CarPark.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarPark.Models.User", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreateByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("ParkingGate");

                    b.Navigation("ParkingLot");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("CarPark.Models.User", b =>
                {
                    b.HasOne("CarPark.Models.User", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateBy");

                    b.HasOne("CarPark.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy");

                    b.HasOne("CarPark.Models.User", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreateByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("CarPark.Models.ParkingGate", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CarPark.Models.ParkingLot", b =>
                {
                    b.Navigation("Gates");

                    b.Navigation("RateRules");
                });
#pragma warning restore 612, 618
        }
    }
}
